version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    #volumes:
    #  - C:\dev\projects-personal\database\postgres\data:/var/lib/postgresql/data
